Add system V script

diff --git a/examples/service/sysv/rygel b/examples/service/sysv/rygel
--- a/examples/service/sysv/rygel
+++ b/examples/service/sysv/rygel
@@ -1,25 +1,7 @@
-#! /bin/sh
-### BEGIN INIT INFO
-# Provides:          rygel
-# Required-Start:    $localfs
-# Required-Stop:     $localfs
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Rygel UPnP-AV server
-# Description:       Start Rygel UPnP server at boot
-### END INIT INFO
+#!/bin/sh
 
-# Author: Jens Georg <mail@jensge.org>
-
-# Do NOT "set -e"
-
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="UPnP-AV device collection"
 NAME=rygel
 DAEMON=/usr/bin/$NAME
-DAEMON_ARGS=""
-PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
@@ -28,12 +10,8 @@ SCRIPTNAME=/etc/init.d/$NAME
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
-
 # Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
 #
@@ -45,15 +23,8 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --no-close --chuid rygel:rygel -b -m --exec $DAEMON -- \
-		$DAEMON_ARGS >/var/log/rygel.log 2>&1\
-		|| return 2
-# Version with private D-Bus
-#	start-stop-daemon --start --quiet --pidfile $PIDFILE --no-close --chuid rygel:rygel -b -m \
-#		--exec /usr/bin/wrap-dbus -- $DAEMON $DAEMON_ARGS >>/var/log/rygel.log 2>&1 \
-#		|| return 2
+	start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null || return 1
+	start-stop-daemon --start --quiet --exec $DAEMON || return 2&
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
@@ -69,7 +40,7 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	start-stop-daemon --stop --quiet --exec $DAEMON --name $NAME
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
@@ -78,29 +49,27 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
 	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
+
 	return "$RETVAL"
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
-do_reload() {
+#do_reload() {
 	#
 	# If the daemon can reload its configuration without
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
 	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
-}
+#}
 
+export DISPLAY=:0
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting " "$NAME"
 	do_start
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -108,7 +77,7 @@ case "$1" in
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping " "$NAME"
 	do_stop
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -116,8 +85,8 @@ case "$1" in
 	esac
 	;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-	;;
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
   #reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
@@ -132,10 +101,11 @@ case "$1" in
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	log_daemon_msg "Restarting " "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
+		sleep 1
 		do_start
 		case "$?" in
 			0) log_end_msg 0 ;;
@@ -144,16 +114,13 @@ case "$1" in
 		esac
 		;;
 	  *)
-		# Failed to stop
+	  	# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
 	exit 3
 	;;
 esac
-
-:
